name: Publish Oxyde.Cloud Loader

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          #VERSIONS
          - name: trixie
            context: trixie
            platforms: linux/amd64,linux/arm64
            tags: |
              trixie
          - name: alpine3.22
            context: alpine3.22
            platforms: linux/amd64,linux/arm64
            tags: |
              alpine3.22
          #VERSIONS
    name: ${{ matrix.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: OxydeCloud
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: OxydeCloud
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            oxydecloud/loader
            ghcr.io/OxydeCloud/Loader
          tags: ${{ matrix.tags }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          platforms: ${{ matrix.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
